version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  ecommerce-api:
    container_name: ecommerce-api
    image: emporium-api:prod
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: ${PORT}
      MONGODB_CONNECTION: ${MONGODB_CONNECTION}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PRIVATE_REFRESH_KEY: ${PRIVATE_REFRESH_KEY}
      NODE_ENV: ${NODE_ENV}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    depends_on:
      - mongodb